config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :pots do
    member do
      patch "/finish", to: "pots#finish"
    end
    get '/thankyou', to: 'pages#thankyou'

    resources :gifts, only: [:new, :create, :destroy]
    member do

      post 'gifts/:gift_id/upvote', to: 'gifts#upvote', as: 'upvote'
      post 'gifts/:gift_id/downvote', to: 'gifts#downvote', as: 'downvote'
    end
    resources :contributions, only: [:new, :create, :show] do
      resources :payments, only: [:new]
    end
  end
  resources :gifts, only: [:edit, :update, :destroy]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  get '/dashboard', to: 'pages#dashboard'


  post 'pots/:id/join', to: "pots#join", as: "join"

  get 'pots/:id/leave', to: "pots#leave", as: "leave"

end

app/views/shared/_carousell.html.erb
<div class="container text-center my-3">
  <h2 class="font-weight-light"><strong>Gift Options</strong></h2>
  <div class="">
    <% if @pot.gifts.any? %>
      <div id="recipeCarousel" class="carousel slide w-100" data-ride="carousel">
        <div class="carousel-inner w-100" role="listbox">
          <div class="carousel-item active">
            <div class="col-md-4">

              <div class="card card-body backlogo", style="background-image: url(<%= @first_gift.photos.first.service_url if @first_gift.photos.any? %>)">

                <h3 class= "card-pot card-pot-empty bgw"><%= @first_gift.name %></h3>
              <%# Votes: <%= @first_gift.votes %>
              <% if current_user.has_voted_in_pot?(@pot) %>
                <% if current_user.has_voted?(@first_gift) %>
                  <%= link_to "Cancel", downvote_pot_path(@pot, @first_gift), class: "bgp-secondary bgw", method: :post %>
                <% end %>
              <% else %>
                <%= link_to "Vote", upvote_pot_path(@pot, @first_gift), class: "bgg bgw", method: :post %>
              <% end %>
            </div>
          </div>
        </div>
        <% @pot.gifts.offset(1).each do |gift| %>
          <div class="carousel-item">
            <div class="col-md-4">

              <div class="card card-body backlogo", style="background-image: url(<%= gift.photos.first.service_url if gift.photos.any? %>)">

                <h3 class= "card-pot card-pot-empty bgw"><%= gift.name %></h3>
                <% if current_user.has_voted_in_pot?(@pot) %>
                  <% if current_user.has_voted?(gift) %>
                    <%= link_to "Cancel", downvote_pot_path(@pot, gift), class: "bgp-secondary bgw", method: :post %>
                  <% end %>
                <% else %>
                  <%= link_to "Vote", upvote_pot_path(@pot, gift), class: "bgg bgw", method: :post %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <a class="carousel-control-prev w-auto" href="#recipeCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next w-auto" href="#recipeCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="flash" class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div id="flash" class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_gift_form.html.erb
<div class= "limiter">
  <div class= "text-center my-3">
    <div class= "wrap-newgift">
      <div class= "newpot-form">
        <span class= "newpot-form-title">
          <h3 class= pb-3>Add a Gift Option</h3>
        </span>
        <div>
          <%= simple_form_for [@pot, @gift] do |f| %>
            <%= f.input :name, label: "Gift's Name", placeholder: "what would you like to offer?", input_html: { autocomplete: "off"} %>
            <%= f.input :price, label: "Price", input_html: { autocomplete: "off"} %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <div class= "container-btn-submit">
              <%= f.submit "Add Gift", class: "btn-bg bgp mt-3" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dzru3xtit/image/upload/v1606407464/logo_ardi_j8cw5l.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home 🏠", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Pots 🎁", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Log Out 🗝", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>