config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :pots do
    member do
      patch "/finish", to: "pots#finish"
    end
    get '/thankyou', to: 'pages#thankyou'

    resources :gifts, only: [:new, :create, :destroy]
    member do

      post 'gifts/:gift_id/upvote', to: 'gifts#upvote', as: 'upvote'
      post 'gifts/:gift_id/downvote', to: 'gifts#downvote', as: 'downvote'
    end
    resources :contributions, only: [:new, :create, :show] do
      resources :payments, only: [:new]
    end
  end
  resources :gifts, only: [:edit, :update, :destroy]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  get '/dashboard', to: 'pages#dashboard'


  post 'pots/:id/join', to: "pots#join", as: "join"

  get 'pots/:id/leave', to: "pots#leave", as: "leave"

end

app/models/pot.rb
class Pot < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  has_many :users_pots, dependent: :destroy
  has_many :users, through: :users_pots

  has_many :gifts, dependent: :destroy
  has_many :gift_votes, through: :gifts

  has_many :contributions, dependent: :destroy

  has_one :chatroom, dependent: :destroy

  validates :name, :end_date, presence: true

  def days_remaining
    date = Date.today
    days_left = (self.end_date - date).to_i
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  before_action :set_pot, only: [:show, :edit, :update, :destroy, :finish, :join]

  def all
    @pots = Pot.order(end_date: :asc)
  end
  
  def index
    @pots = Pot.all
  end

  def show
    @first_gift = @pot.gifts.first
    # @ordered_gifts = @pot.gifts.joins(:gift_votes).group(:id, :gift_votes).order(:gift_votes)
    @ordered_gifts = @pot.gifts.left_joins(:gift_votes).group(:id).select('gifts.*', 'COUNT(gift_votes.id) vote_count').order('vote_count DESC')
    @winner_gift = @ordered_gifts.first
    @gift = Gift.new
    @contribution = Contribution.where(user: current_user, pot: @pot).first
    @user = current_user
  end

  def new
    @pot = Pot.new
  end

  def create
    @pot = Pot.new(pot_params)
    @pot.owner = current_user
    @pot.chatroom = Chatroom.create(name: "#{@pot.name}'s Chatroom")

    if @pot.save
      redirect_to pot_path(@pot.id), notice: "Well done!! You just created a POT"
    else
      render :new
    end
  end


  # def edit
  # end

  # def update
  #   @pot.update(pot_params)
  # end

  def finish
    @pot.active = false
    @pot.save
    redirect_to pot_path(@pot)
  end

  def destroy
    @pot.destroy
    redirect_to dashboard_path
  end

  def join
    @user = current_user
    if @pot.users.include? @user
      redirect_to pot_path(@pot), alert: "You already a member of this pot"
    else
      @users_pot = UsersPot.create(pot: @pot, user: @user)
      @users_pot.save
      redirect_to pot_path(@pot), notice: "You successfully joined this pot"
    end
  end

  def destroy
    @pot.destroy
    redirect_to dashboard_path
  end

  def leave
    @user = current_user
    set_pot
    if @pot.users.include? @user
      @users_pot = UsersPot.find_by user: current_user
      @users_pot.destroy
      redirect_to dashboard_path, notice: "You successfully left #{@pot.name}"
    else
      redirect_to pot_path(@pot), alert: "You aren't a member of this pot"
    end
  end

  private

  def pot_params
    params.require(:pot).permit(:name, :description, :min_amount, :end_date, :owner)
  end

  def set_pot
    @pot = Pot.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(:amount)
  end
end

app/views/pots/form.html.erb
<h1>Create your POT</h1>

<%= simple_form_for(pot) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :min_amount %>
  <%= f.submit %>
<% end %>

app/views/pots/new.html.erb
<div class= "limiter">
  <div class= "container-newpot">
    <div class= "wrap-newpot">
      <div class= "newpot-form">
        <span class= "newpot-form-title p-b-66">
          Create New Pot
        </span>
        <div>
          <%= simple_form_for(@pot)do |f| %>
            <%= f.input :name, label: "Pot name", placeholder: "B-day, Farewell party, Wedding gift, Christmas present... ", input_html: { autocomplete: "off"} %>
            <%= f.input :end_date, as: :string, placeholder: "DD/MM/YYYY", label: "Pot closing date:".html_safe, input_html: { class: "datepicker" } %>
            <%= f.input :description, label: "Description:", placeholder: "Lets others know more details about your idea", input_html: { autocomplete: "off"} %>
            <%= f.input :min_amount, label: "Minimum contribution:" %>
            <div class= "container-btn-submit">
              <%= f.submit "Create Pot", class: "btn-bg bgp mt-3" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pots/show.html.erb
<div class="container text-center my-3">
  <div class="d-flex justify-content-between">
  <% if  @pot.owner == current_user && @pot.active == false %>
    <%= link_to '<i class="fas fa-arrow-left fa-1x" style="color:black"></i>'.html_safe, dashboard_path  %>
    <%= link_to '<i class="far fa-window-close fa-1x" style="color:black"></i>'.html_safe, pot_path(@pot), method: :delete, data:{confirm: "Are you sure you want to delete the pot FOREVER??"} %>
  <% elsif @pot.owner == current_user %>
    <%= link_to '<i class="fas fa-arrow-left fa-1x" style="color:black"></i>'.html_safe, dashboard_path  %>
    <%= link_to '<i class="far fa-window-close fa-1x" style="color:black"></i>'.html_safe, finish_pot_path(@pot), method: :patch, data:{confirm: "Are you sure you want to permanantly close the pot and cash-out 💰??"} %>
  <% else %>
    <%= link_to '<i class="fas fa-arrow-left" style="color:black"></i>'.html_safe, dashboard_path  %>
  <% end %>
  </div>
  <div class="card p-2 bgt">
  <h2><%= @pot.name.capitalize %></h2>


    <% if @pot.active == false %>
      <div class="card p-2 bgp">
        <p><%= @pot.description %></p>
        <h3> Gift Date ➼ <%= @pot.end_date.strftime("%d %b %Y") %></h3>
        <h2> Total raised: <strong><%= @pot.total_amount/100 %>€</strong></h2>
        <% if (@pot.owner.contributions.where pot_id:(@pot)).last != nil %>
          <p><%= @pot.owner.first_name %> <%= @pot.owner.last_name %> - Contribution: <%= (@pot.owner.contributions.where pot_id:(@pot)).last.amount_cents/100 %>€</p>
        <% end %>
        <% @pot.users.each do |user| %>
          <% if (user.contributions.where pot_id:(@pot)).last != nil %>
            <p><%= user.first_name %> <%= user.last_name %> - Contribution: <%= (user.contributions.where pot_id:(@pot)).last.amount_cents/100 %>€</p>
          <% end %>
        <% end %>
      </div>
      <div class="card p-2 mt-2 pink">
        <% if @winner_gift != nil %>
          <h3> The winning gift 🎁</h3>
          <h2> <strong><%= @winner_gift.name %></strong> with <strong><%= @winner_gift.votes %></strong> votes.</h2>
        <% else %>
          <h2> NO GIFTS 😥</h2>
        <% end %>
      </div>
      <div class="container mt-2">
        <%= link_to '<i class="far fa-comments fa-2x" style="color:white"></i>'.html_safe, chatroom_path(@pot.chatroom.id), class: "btn-sqr bgy" %>
      </div>
    <% else %>

          <%#= CHECKING IF OWNER/MEMBER/NON-MEMBER AND DISPLAYING LINK TO SHARE OR JOIN ACCORDINGLY %>
      <% if @pot.owner == current_user || (@pot.users_pots.where user_id:(current_user)).exists? %>
          <%= link_to 'Invite to Pot'.html_safe, "whatsapp://send?text=I’m%20raising%20for%20a%20gift%20and%20I%20think%20you’d%20like%20to%20be%20part%20of%20it%20-%20join%20my%20pot:%20#{request.original_url}", class: "btn-inv" %>
      <% else %>
          <%= link_to "Join Pot", join_path(@pot), method: :post, class: "btn-inv-strong" %>
      <% end %>

      <div class="card p-2">
        <p><%= @pot.description %></p>
        <% if @pot.days_remaining == 0 %>
          <p>Pot is ending today!</p>
        <% elsif @pot.days_remaining == 1 %>
          <p>Date: <%= @pot.end_date.strftime("%d %b %Y")%> ➼ <strong><%= @pot.days_remaining %> Day left</strong> </p>
        <% elsif @pot.days_remaining > 0 %>
          <p>Date: <%= @pot.end_date.strftime("%d %b %Y")%> ➼ <strong><%= @pot.days_remaining %> Days left</strong> </p>
        <% end %>
        <h2><strong>💰 <%= @pot.total_amount/100 %>€ raised 💰</strong></h2>
        <% @pot.contributions.each do |contribution| %>
          <p>€<%= contribution.amount_cents/100 %> contributed by <%= contribution.user.first_name %> <%= contribution.user.last_name %></p>
        <% end %>
        <% unless Contribution.where(user: current_user, pot: @pot).exists? %>
          <div class="cont-btn"><%= link_to '<i class="fas fa-hand-holding-usd fa-2x"></i>'.html_safe, new_pot_contribution_path(@pot) %></div>
        <% end %>
      </div>
      <div class= "card-pot px-2 py-1 card-pot-empty">
        <% @ordered_gifts.each do |gift| %>
          <ul>
            <li class="d-flex justify-content-between align-items-center mt-1">
              <span class="badge badge-primary badge-pill">Votes: <%= gift.votes %></span>
              <%= gift.name.capitalize %> - €<%= gift.price %>
              <% if @pot.owner == current_user %>
              <%= link_to '<i class="fas fa-trash" style="color:#D20E85"></i>'.html_safe, gift_path(gift), method: :delete %>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
      <% if @pot.owner == current_user %>


      <%= render 'shared/carousell' %>
        <div class="container mt-2 d-flex justify-content-between mt-3">
          <p>
            <a class="btn-sqr bgp" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              <i class="fas fa-gift fa-2x" style="color:white"></i>
            </a>
          </p>
          <div class="collapse" id="collapseExample">
            <%= render 'shared/gift_form' %>
        </div>
      <%= link_to'<i class="far fa-comments fa-2x" style="color:white"></i>'.html_safe, chatroom_path(@pot.chatroom.id), class: "btn-sqr bgp" %>
        <% else %>
          <%= render 'shared/carousell' %>
          <div class="container mt-2 d-flex justify-content-around">
            <%= link_to '<i class="fas fa-sign-out-alt fa-2x" style="color:white"></i>'.html_safe, leave_path(@pot), class: "btn-sqr bgp", data:{confirm: "🏃‍♀️🏃‍♂️ Are you sure you whant to leave the pot FOREVER?? 🏃‍♀️🏃‍♂️"} %>
            <%= link_to '<i class="far fa-comments fa-2x" style="color:white"></i>'.html_safe, chatroom_path(@pot.chatroom.id), class: "btn-sqr bgp" %>
          </div>
        <% end %>
    <% end %>
  </div>
</div>
<div class="list-group">
  <button type="button" class="list-group-item list-group-item-action active">
    Owner - <%= @pot.owner.first_name %> <%= @pot.owner.last_name %>
  </button>
  <% @pot.users.each do |user| %>
    <button type="button" class="list-group-item list-group-item-action">
      Member - <%= user.first_name %> <%= user.last_name %>
    </button>
  <% end %>
</div>