config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :pots do
    member do
      patch "/finish", to: "pots#finish"
    end
    get '/thankyou', to: 'pages#thankyou'

    resources :gifts, only: [:new, :create, :destroy]
    member do

      post 'gifts/:gift_id/upvote', to: 'gifts#upvote', as: 'upvote'
      post 'gifts/:gift_id/downvote', to: 'gifts#downvote', as: 'downvote'
    end
    resources :contributions, only: [:new, :create, :show] do
      resources :payments, only: [:new]
    end
  end
  resources :gifts, only: [:edit, :update, :destroy]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  get '/dashboard', to: 'pages#dashboard'


  post 'pots/:id/join', to: "pots#join", as: "join"

  get 'pots/:id/leave', to: "pots#leave", as: "leave"

end

app/views/pages/_dashboard.erb
<div class="dash-container">
  <div class="show-text">
    <h2><%= @user.first_name %>'s Dashboard</h2>
  </div>

  <div class="dash-section">
    <h3 class= "text-center"> Pots Where <%= @user.first_name %> is Owner </h3>

    <% if @user.pots.count != 0 %>
      <% @user.pots.each do |pot| %>
        <ul>
          <li> <%= pot.name %></li>
          <li> to code: remaining time, contributors or members, cash raised </li>
        </ul>
      <% end %>
    <% else %>
      <ul>
        <li> <%="You're not leading any pots" %> </li>
      </ul>
    <% end %>
  </div>

  <div class="dash-section">
    <h3 class= "text-center"> Pots Where <%= @user.first_name %> is a Member </h3>

    May need to change schema for this?

    <% if @user.userspots.count != 0 %>
      <% @user.userspots.each do |userpot| %>
        <ul>
          <li> <%= pot.name %></li>
          <li> to code: remaining time, contributors or members, cash raised </li>
        </ul>
      <% end %>
    <% else %>
      <ul>
        <li> <%="You're not taking part in any pots" %> </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<h2 class= "dash-title"> My Pots</h2>

<h3 class= "text-center"> Owned Pots </h3>
<% if @user.owned_pots.count != 0 %>
  <% @ordered_pots.each do |pot| %>
    <%= link_to pot_path(pot) do %>
    <div class="card-pot bgy">
      <div class="card-pot-infos">
        <div>
          <h2><%= pot.name %> </h2>
          <% if pot.active == false %>
            <p>Pot ended! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
          <% else %>
            <% if  pot.days_remaining == 0%>
              <p>Pot is ending today! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% elsif pot.days_remaining < 0 %>
              <p>Pot ended! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% elsif pot.days_remaining == 1 %>
              <p><%= pot.days_remaining %> day left - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% else %>
              <p><%= pot.days_remaining %> days left - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% end %>
          <% end %>
        </div>
      </div>
        <% if pot.active == true %>
        <button class= "card-pot-delete-btn">
            <%= link_to finish_pot_path(pot), method: "patch", data:{confirm: "Are you sure you want to finish the pot FOREVER 😥??"} do %>
              <i class="fas fa-check-circle" style="color:white"></i>
            <% end %>
        </button>
        <% else %>
        <button class= "card-pot-delete-btn">
            <%= link_to pot_path(pot), method: "delete", data:{confirm: "Are you sure you want to permanantly close the pot and cash-out 💰??"} do %>
              <i class="fas fa-trash" style="color:white"></i>
            <% end %>
        </button>
        <% end %>
    </div>
    <% end %>
  <% end %>
<% else %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span>You're not leading any pots! 💰 <%= link_to "Create Pot now!", new_pot_path %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<h3 class= "text-center"> Joined Pots </h3>
<% if @user.pots.count != 0 %>
  <% @user.pots.each do |pot| %>
    <%= link_to pot_path(pot) do %>
    <div class="card-pot bgt">
      <div class="card-pot-infos">
        <div>
          <h2><%= pot.name %> </h2>
          <% if pot.active == false %>
            <p>Pot ended! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
          <% else %>
            <% if  pot.days_remaining == 0%>
              <p>Pot is ending today! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% elsif pot.days_remaining < 0 %>
              <p>Pot ended! - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% elsif pot.days_remaining == 1 %>
              <p><%= pot.days_remaining %> day left - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
          <% else %>
            <p><%= pot.days_remaining %> days left - <strong>€<%= pot.total_amount/100 %></strong> raised</p>
            <% end %>
          <% end %>
        </div>
        <%# <% if pot.active == true %>
        <button class= "card-pot-delete-btn">
          <%= link_to leave_path(pot), method: :get, data:{confirm: "🏃‍♀️🏃‍♂️ Are you sure you whant to leave the pot FOREVER?? 🏃‍♀️🏃‍♂️"} do %>
            <i class="fas fa-sign-out-alt" style="color:white"></i>
          <% end %>
        </button>
        </div>
      </div>
    <% end %>
  <%end %>
      <% else %>

  <ul>
    <li><%="You're not taking part in any pots" %> </li>
  </ul>
<% end %>
  </div>

</div>
<div class= "container-btn-submit row justify-content-center ml-3 mr-3">
  <button type= "button" class="btn-bg bgp mt-3 centered"> <%= link_to "Create Pot", new_pot_path %></button>
</div>

app/views/pages/home.html.erb
<body>
  <div class="home-banner">
    <div class="home-logo">
      <img src="https://res.cloudinary.com/dzru3xtit/image/upload/v1606407464/logo_ardi_j8cw5l.png" style= "width: 100px">
    </div>
    <div class="home-text">
      <h2>Welcome To</h2>
      <h1>GiftPot</h1>
    </div>

    <div class="home-text">
      <h3 class="px-3">The hassle-free solution to aggregate contributions </h3>
    </div>
    <div class="d-flex justify-content-around mb-3" style="flex-direction: column" >

        <% if user_signed_in? %>
          <p class="home-buttons"><%= link_to "Create Pot", new_pot_path, class: "blue-btn" %></p>
          <p class= "home-buttons"><%= link_to "My Pots", dashboard_path, class: "blue-btn" %></p>
          <p class= "home-buttons"><%#= link_to "Chat", chatrooms_path, class: "blue-btn" %></p>
        <% else %>
          <p class="home-buttons"><%= link_to "Get Started", dashboard_path, class: "blue-btn" %></p>
         <!--  <p class= "home-buttons"><%= link_to "Log In", new_user_session_path, class: "blue-btn" %></p> -->
        <% end %>
    </div>
  </div>
</body>

app/views/pages/thankyou.html.erb
<h1> Thankyou for your contribution </h1>